

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.Statement;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author USUARIO
 */
public class Translations extends javax.swing.JFrame {

    
    int ID;
    static Connection con;
    static Statement stmt;
    
    /**
     * Creates new form Translations
     */
    public Translations() {
        initComponents();
        t1 = new TextPrompt("Enter Translation", trans1);
        t2 = new TextPrompt("Enter Translation", trans2);
        t3 = new TextPrompt("Enter Translation", trans3);
        t4 = new TextPrompt("Enter Translation", trans4);
        t5 = new TextPrompt("Enter Translation", trans5);
        t6 = new TextPrompt("Enter Translation", trans6);
        t7 = new TextPrompt("Enter Translation", trans7);
        t8 = new TextPrompt("Enter Translation", trans8);
        t9 = new TextPrompt("Enter Translation", trans9);
        t10 = new TextPrompt("Enter Translation", trans10);
        t11 = new TextPrompt("Enter EXTRA translation ", extra);
        this.con = Conexion.conexion();
        this.stmt = Conexion.stm();
        this.ID = Conexion.getLastId("translation","Translation_ID");
     
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        trans9 = new javax.swing.JTextField();
        trans1 = new javax.swing.JTextField();
        trans10 = new javax.swing.JTextField();
        trans2 = new javax.swing.JTextField();
        trans8 = new javax.swing.JTextField();
        trans3 = new javax.swing.JTextField();
        close = new javax.swing.JButton();
        add = new javax.swing.JButton();
        erase = new javax.swing.JButton();
        trans7 = new javax.swing.JTextField();
        trans4 = new javax.swing.JTextField();
        trans5 = new javax.swing.JTextField();
        trans6 = new javax.swing.JTextField();
        lan1 = new javax.swing.JComboBox();
        lan3 = new javax.swing.JComboBox();
        lan4 = new javax.swing.JComboBox();
        lan2 = new javax.swing.JComboBox();
        lan5 = new javax.swing.JComboBox();
        lan7 = new javax.swing.JComboBox();
        lan8 = new javax.swing.JComboBox();
        lan9 = new javax.swing.JComboBox();
        lan6 = new javax.swing.JComboBox();
        lan10 = new javax.swing.JComboBox();
        extra = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 255, 204));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setText("TRANSLATIONS");

        trans1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                trans1ActionPerformed(evt);
            }
        });

        close.setText("Close");
        close.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeActionPerformed(evt);
            }
        });

        add.setText("Add");
        add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addActionPerformed(evt);
            }
        });

        erase.setText("Erase fields");
        erase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eraseActionPerformed(evt);
            }
        });

        lan1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "br", "de", "es", "fa", "fr", "hr", "it", "ja", "nl", "pt", " " }));
        lan1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lan1ActionPerformed(evt);
            }
        });

        lan3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "br", "de", "es", "fa", "fr", "hr", "it", "ja", "nl", "pt", " " }));
        lan3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lan3ActionPerformed(evt);
            }
        });

        lan4.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "br", "de", "es", "fa", "fr", "hr", "it", "ja", "nl", "pt", " " }));
        lan4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lan4ActionPerformed(evt);
            }
        });

        lan2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "br", "de", "es", "fa", "fr", "hr", "it", "ja", "nl", "pt", " " }));
        lan2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lan2ActionPerformed(evt);
            }
        });

        lan5.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "br", "de", "es", "fa", "fr", "hr", "it", "ja", "nl", "pt", " " }));
        lan5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lan5ActionPerformed(evt);
            }
        });

        lan7.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "br", "de", "es", "fa", "fr", "hr", "it", "ja", "nl", "pt", " " }));
        lan7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lan7ActionPerformed(evt);
            }
        });

        lan8.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "br", "de", "es", "fa", "fr", "hr", "it", "ja", "nl", "pt", " " }));
        lan8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lan8ActionPerformed(evt);
            }
        });

        lan9.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "br", "de", "es", "fa", "fr", "hr", "it", "ja", "nl", "pt", " " }));
        lan9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lan9ActionPerformed(evt);
            }
        });

        lan6.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "br", "de", "es", "fa", "fr", "hr", "it", "ja", "nl", "pt", " " }));
        lan6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lan6ActionPerformed(evt);
            }
        });

        lan10.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "br", "de", "es", "fa", "fr", "hr", "it", "ja", "nl", "pt", " " }));
        lan10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lan10ActionPerformed(evt);
            }
        });

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setText("In case there are more than 10 translations\nan extra text field is provided\n\nEnter (all) other extra translation(s) \nfollowed by the language like this\n\ntranslation;languageprefix/\ni.e: the translation of argentina in french is\nArgentine;fr/");
        jScrollPane1.setViewportView(jTextArea1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(trans3, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(lan3, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(trans2, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(trans1, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(trans4, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(trans5, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(trans6, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(trans7, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(trans8, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(trans9, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(trans10, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(lan9, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lan8, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lan7, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lan6, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lan4, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lan2, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lan1, javax.swing.GroupLayout.Alignment.LEADING, 0, 92, Short.MAX_VALUE)
                            .addComponent(lan5, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lan10, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(close, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(add, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(erase, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 378, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 38, Short.MAX_VALUE))))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 331, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(208, 208, 208))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(extra, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(478, 478, 478))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(trans1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lan1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(trans2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(close, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lan2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(trans3, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lan3, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(trans4, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lan4, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(trans5, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lan5, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(add, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(trans6, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lan6, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(trans7, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lan7, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(trans8, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lan8, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addComponent(erase, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(trans9, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lan9, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(trans10, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lan10, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addComponent(extra, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(41, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lan10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lan10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lan10ActionPerformed

    private void lan6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lan6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lan6ActionPerformed

    private void lan9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lan9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lan9ActionPerformed

    private void lan8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lan8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lan8ActionPerformed

    private void lan7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lan7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lan7ActionPerformed

    private void lan5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lan5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lan5ActionPerformed

    private void lan2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lan2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lan2ActionPerformed

    private void lan4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lan4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lan4ActionPerformed

    private void lan3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lan3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lan3ActionPerformed

    private void lan1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lan1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lan1ActionPerformed

    private void closeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeActionPerformed

        this.setVisible(false); 
        // TODO add your handling code here:
    }//GEN-LAST:event_closeActionPerformed

    private void trans1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_trans1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_trans1ActionPerformed

    private void eraseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eraseActionPerformed
        // TODO add your handling code here:
        trans1.setText("");
        trans2.setText("");
        trans3.setText("");
        trans4.setText("");
        trans5.setText("");
        trans6.setText("");
        trans7.setText("");
        trans8.setText("");
        trans9.setText("");
        trans10.setText("");
        extra.setText("");
    }//GEN-LAST:event_eraseActionPerformed

    private void addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addActionPerformed
        // TODO add your handling code here:
        try{
            PreparedStatement ps =con.prepareStatement("INSERT INTO `countries-reto`.`translation`(`Translation_ID`,`Translations`)VALUES(?,?)");
            ps.setInt(1,ID);
            String str1 = 
                    trans1.getText()+ ";"+ (String)lan1.getSelectedItem() + "/" +
                    trans2.getText()+ ";"+ (String)lan2.getSelectedItem() + "/" +
                    trans3.getText()+ ";"+ (String)lan3.getSelectedItem() + "/" +
                    trans4.getText()+ ";"+ (String)lan4.getSelectedItem() + "/" +
                    trans5.getText()+ ";"+ (String)lan5.getSelectedItem() + "/" +
                    trans6.getText()+ ";"+ (String)lan6.getSelectedItem() + "/" +
                    trans7.getText()+ ";"+ (String)lan7.getSelectedItem() + "/" +
                    trans8.getText()+ ";"+ (String)lan8.getSelectedItem() + "/" +
                    trans9.getText()+ ";"+ (String)lan9.getSelectedItem() + "/" +
                    trans10.getText()+ ";"+ (String)lan10.getSelectedItem() +
                    extra.getText()
                    ;
            ps.setString(2,str1);
          
            ps.executeUpdate();
           
        }
        catch(Exception e){ 
            System.out.println(e);
        }
         this.dispose();
    }//GEN-LAST:event_addActionPerformed

    
     TextPrompt t1;
     TextPrompt t2;
     TextPrompt t3 ;
     TextPrompt t4 ;
     TextPrompt t5 ;
     TextPrompt t6;
     TextPrompt t7 ;
     TextPrompt t8 ;
     TextPrompt t9 ;
     TextPrompt t10 ;
     TextPrompt t11 ; 
       

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton add;
    private javax.swing.JButton close;
    private javax.swing.JButton erase;
    private javax.swing.JTextField extra;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JComboBox lan1;
    private javax.swing.JComboBox lan10;
    private javax.swing.JComboBox lan2;
    private javax.swing.JComboBox lan3;
    private javax.swing.JComboBox lan4;
    private javax.swing.JComboBox lan5;
    private javax.swing.JComboBox lan6;
    private javax.swing.JComboBox lan7;
    private javax.swing.JComboBox lan8;
    private javax.swing.JComboBox lan9;
    private javax.swing.JTextField trans1;
    private javax.swing.JTextField trans10;
    private javax.swing.JTextField trans2;
    private javax.swing.JTextField trans3;
    private javax.swing.JTextField trans4;
    private javax.swing.JTextField trans5;
    private javax.swing.JTextField trans6;
    private javax.swing.JTextField trans7;
    private javax.swing.JTextField trans8;
    private javax.swing.JTextField trans9;
    // End of variables declaration//GEN-END:variables
}
